# -*- coding: utf-8 -*-
"""tweetStreamCursor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jEbYCfLG4pYtCk7DwopndE4VuzLJwiJb
"""

import tweepy
import pandas as pd
import csv

NUM_ITEMS = 200

CONSUMER_KEY = "******************"
CONSUMER_SECRET = "******************"
ACCESS_TOKEN = "******************"
ACCESS_TOKEN_SECRET = "******************"

SEARCH_WORDS_LIST = ["covid vaccine unsafe", "covid vaccine already had covid", "covid vaccine choice", "covid vaccine freedom",
                     "covid vaccine ineffective", "covid vaccine not serious health risk", "covid vaccine no access", "covid vaccine dangerous",
                     "covid fake", "covid vaccine already infected", "covid vaccine unproven", "covid vaccine dangerous side effects", "covid vaccine natural immunity"]

def getTweets(api, searchWords, dateSince):
  tweets_list = []
  for tweets in tweepy.Cursor(api.search, q=searchWords, lang="en", since=dateSince, tweet_mode="extended").items(NUM_ITEMS):
    temp_list = []
    if 'retweeted_status' in dir(tweets):
      tweet = tweets.retweeted_status.full_text
    else:
      tweet = tweets.full_text

    tweet = tweet.replace('\n', ' ').replace('\r', '')
    temp_list.append(tweet)
    tweets_list.append(temp_list)

  df = pd.DataFrame(tweets_list, columns=['Text'])

  return df

startDf = pd.read_csv('LiveStreamedTweets.csv', delimiter=',')
print("\nLength of startDf: ", len(startDf))

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

try:
  api.verify_credentials()
  print("Authentication OK")
except:
  print("Error during authentication")

for searchWords in SEARCH_WORDS_LIST:
  print("\n\n", searchWords)
  searchWordDf = getTweets(api, searchWords, "2020-06-21")
  searchWordDf.to_csv('LiveStreamedTweets.csv', mode='a', header=False, index=False)

endDf = pd.read_csv('LiveStreamedTweets.csv', delimiter=',')
for index, row in endDf.iterrows():
  print(row[0])
  print(type(row[0]))
  print(type(row[0]) is str)
  print("---------------------------\n\n")

print("\nInitial length of LiveStreamedTweets.csv: ", len(startDf))
print("\nExpected length of endDf: ", len(startDf)+(NUM_ITEMS*len(SEARCH_WORDS_LIST)))
print("\nNum tweets added: ", NUM_ITEMS*len(SEARCH_WORDS_LIST))
